server:
  port: 8205

spring:
  cloud:
    sentinel:
      transport:
        dashboard: http://192.168.200.188:8858
#阿里云 OSS
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI4FhtGRtRGtPvmLBv8vxk
      keysecret: sq8e8WLYoKwJoCNLbjRdlSTaOaFumD
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: online-teach-file
