server:
  port: 8205

spring:
  cloud:
    sentinel:
      transport:
        dashboard: http://127.0.0.1:8333
#阿里云 OSS
#aliyun:
#  oss:
#    endpoint: oss-cn-hongkong.aliyuncs.com
#    keyid: LTAI4GHDJxDbSZfWqyHE6UMh
#    keysecret: EQkQ0tQpXTYbZU3hY3h65iEACdz5CN
#    #bucket可以在控制台创建，也可以使用java代码创建
#    bucketname: mma-tseng


