management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8204

spring:
  cloud:
    sentinel:
      transport:
        dashboard: http://127.0.0.1:8333
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.56.10
#阿里云 短信
aliyun:
  sms:
    regionId: default
    accessKeyId: LTAI0YbQf3pX8WqC
    secret: jX8D04DmDI3gGKjW5kaFYSzugfqmmT

#互动资通短信
mma:
  sms:
    sendSMSUrl: http://api.every8d.com/API21/HTTP/sendSMS.ashx
    getCreditUrl: http://api.every8d.com/API21/HTTP/getCredit.ashx
    credit: 0
    userID: 0986052168
    password: dgb7
    subject: 预约挂号统一平台验证码：
