management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8204

spring:
  cloud:
    sentinel:
      transport:
        dashboard: http://139.198.114.54:8858
  rabbitmq:
    host: 139.198.114.54
    port: 5672
    virtual-host: /
    username: admin
    password: admin
  redis:
    host: 139.198.114.54
#阿里云 短信
aliyun:
  sms:
    regionId: default
    accessKeyId: LTAI0YbQf3pX8WqC
    secret: jX8D04DmDI3gGKjW5kaFYSzugfqmmT
