server:
  port: 8204

spring:
  cloud:
    sentinel:
      transport:
        dashboard: http://192.168.200.188:8858
  rabbitmq:
    host: 192.168.200.188
    port: 5672
    username: admin
    password: admin
  redis:
    host: 192.168.200.188
#阿里云 短信
aliyun:
  sms:
    regionId: default
    accessKeyId: LTAI0YbQf3pX8WqC
    secret: jX8D04DmDI3gGKjW5kaFYSzugfqmmT
