server:
  port: 8204

spring:
  cloud:
    sentinel:
      transport:
        dashboard: http://127.0.0.1:8333
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /
    username: guest
    password: guest
  redis:
    host: 192.168.56.10
#阿里云 短信
aliyun:
  sms:
    regionId: default
    accessKeyId: LTAI0YbQf3pX8WqC
    secret: jX8D04DmDI3gGKjW5kaFYSzugfqmmT
