server:
  port: 8207
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.200.188:8858
  rabbitmq:
    host: 192.168.200.188
    port: 5672
    username: admin
    password: admin