management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8207
spring:
  cloud:
    sentinel:
      transport:
        dashboard: http://127.0.0.1:8333
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    username: guest
    password: guest